# Generated by Django 4.2.3 on 2023-10-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Seminars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seminar_title', models.CharField(max_length=200)),
                ('Seminar_Date', models.DateField()),
                ('Seminar_Time', models.TimeField()),
                ('Seminar_Venue', models.CharField(blank=True, max_length=1000)),
                ('Venue_location', models.CharField(max_length=200)),
                ('Venue_offline_location', models.CharField(max_length=200)),
                ('Technology_tags', models.CharField(max_length=200)),
                ('Host_Company', models.CharField(max_length=200)),
                ('Links', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MockTest_id', models.CharField(max_length=1000)),
                ('CompanyName', models.CharField(max_length=1000)),
                ('companylogo', models.ImageField(upload_to='')),
                ('Role_desc', models.CharField(max_length=1000)),
                ('Technology_tag', models.CharField(max_length=200)),
                ('Question_1', models.CharField(max_length=1000)),
                ('Answer_1', models.CharField(max_length=1000)),
                ('Question_2', models.CharField(max_length=1000)),
                ('Answer_2', models.CharField(max_length=1000)),
                ('Question_3', models.CharField(max_length=1000)),
                ('Answer_3', models.CharField(max_length=1000)),
                ('Question_4', models.CharField(max_length=1000)),
                ('Answer_4', models.CharField(max_length=1000)),
                ('Question_5', models.CharField(max_length=1000)),
                ('Answer_5', models.CharField(max_length=1000)),
            ],
        ),
    ]
