# Generated by Django 4.2.3 on 2023-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpoweradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_seminars',
            name='Seminar_Date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post_seminars',
            name='Seminar_Time',
            field=models.CharField(max_length=200),
        ),
    ]
