# Generated by Django 4.2.3 on 2023-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpoweradmin', '0002_alter_post_seminars_seminar_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_seminars',
            name='Venue_offline_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
