# Generated by Django 4.2.3 on 2023-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpoweradmin', '0003_alter_post_seminars_venue_offline_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_seminars',
            name='venue_offline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
