# Generated by Django 4.2.3 on 2023-10-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpoweradmin', '0004_post_seminars_venue_offline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_seminars',
            name='Venue_offline_location',
        ),
    ]
