# Generated by Django 4.2.3 on 2023-10-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpoweradmin', '0005_remove_post_seminars_venue_offline_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_seminars',
            name='Venue_offline_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post_seminars',
            name='Seminar_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post_seminars',
            name='Seminar_Time',
            field=models.TimeField(),
        ),
    ]
